library(devtools)
library(knitr)
library(rmarkdown)
library(xtable)
library(ggplot2)
library(glmnet)
library(pls)

sink("../../data/generated_data/session-info.txt", append = TRUE)
cat("Session Information\n\n")
print(sessionInfo())
devtools::session_info()
sink()