.PHONY: clean all data
#Input data to be cleaned
raw_data = data/input_data/MERGED2014_15_PP.csv

#Phony data target to make clean data
data: data/generated_data/clean_data.csv data/generated_data/scaled_data.csv


#runs script that scales data
data/generated_data/scaled_data.csv: data/generated_data/clean_data.csv
	Rscript code/scripts/data_process.R $^

#runs script that cleans and formats data
data/generated_data/clean_data.csv:
	Rscript code/scripts/data_clean.R $(raw_data)

#creates a text files with exploratory data analysis information of data set
eda.txt: data/generated_data/clean_data.csv
	Rscript code/scripts/eda.R $^ $(raw_data)


#generates session information to stdout
session:
	bash session.sh

#delete data generated by processes in the project
clean:
	rm data/generated_data/*