.PHONY: clean all data
#Input data to be cleaned
raw_data = data/input_data/MERGED2014_15_PP.csv

#Phony data target to make clean data
data: data_clean.R

#script that cleans data
data_clean.R:
	Rscript code/scripts/data_clean.R $(raw_data)

#creates a text files with exploratory data analysis information of data set
eda.txt: data_clean.R
	Rscript code/scripts/eda.R $^ $(raw_data)


#generates session information to stdout
session:
	bash session.sh

#delete data generated by processes in the project
clean:
	rm data/generated_data/*