
<<setup, include=FALSE, cache=FALSE, echo=FALSE>>=
library(knitr)
# set global chunk options

@

\section{Introduction}
Suppose we are Public Policy Researchers hired by the government. The government is interested in boosting graduation rates across the nation. However, its resources are limited, and the government is not sure how to spend its money. As a result, we are tasked with determining which factors affect a college’s graduation rate the most. Our task is first to identify potential “good apple” colleges based on their graduation rates from the College Scorecard data. From there, we could analyze each “good apple” college, and perform necessary data analysis to come up with a competent solution.
