
<<setup, include=FALSE, cache=FALSE, echo=FALSE>>=
library(knitr)
# set global chunk options

@

\section{Introduction}
Suppose we are Public Policy Researchers hired by the government. The government is interested in boosting graduation rates across the nation. However, its resources are limited, and the government is not sure how to spend its money. As a result, we are tasked with determining which variables affect a college’s graduation rate the most. In addition, the government wants to see how these variables might change if we were to look at graduation rates of people with different ethnicities. For instance, are the variables that affect Black people's graduation rates the same as the variables that affect Asian people's graduation rates? In order to answer these questions, the government wants us to build an interactive web application that allows a non-technical user to find the relevant variables for a specific ethnicity's graduation rates. 